global:

route:
  receiver: "hawkular-alerts"
  group_by: ['alertname', 'tenant']
  group_wait:      10s
  group_interval:  1m
  repeat_interval: 2m

receivers:
- name: "hawkular-alerts"
  webhook_configs:
  - url: 'http://localhost:8080/hawkular/alerter/prometheus/notification'
    send_resolved: false
